// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/31/2024, 10:07:46 PM
const configMerger = require("/Users/emanuilgerganov/dev/guest-house/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/emanuilgerganov/dev/guest-house/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/emanuilgerganov/dev/guest-house/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/emanuilgerganov/dev/guest-house/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/emanuilgerganov/dev/guest-house/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/emanuilgerganov/dev/guest-house/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/emanuilgerganov/dev/guest-house/plugins/**/*.{js,ts,mjs}","/Users/emanuilgerganov/dev/guest-house/composables/**/*.{js,ts,mjs}","/Users/emanuilgerganov/dev/guest-house/utils/**/*.{js,ts,mjs}","/Users/emanuilgerganov/dev/guest-house/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/emanuilgerganov/dev/guest-house/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/emanuilgerganov/dev/guest-house/app.config.{js,ts,mjs}"] }));

module.exports = config
